# Generated by Django 5.1 on 2025-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_tweet_photo_remove_tweet_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='Available', max_length=50),
        ),
    ]
