# Generated by Django 5.1 on 2025-01-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_remove_tweet_name_tweet_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='document_images/'),
        ),
    ]
