# Generated by Django 5.1 on 2025-01-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
