# Generated by Django 5.1 on 2025-01-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_tweet_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
