# Generated by Django 5.1 on 2025-01-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_alter_tweet_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=10),
        ),
    ]
